/ http://www.math.bas.bg/bantchev/place/k.html
/ K crash course https://github.com/kparc/kcc

activity: 0: <`"data/activity.csv"
address: 0: <`"data/address.csv"
branch: 0: <`"data/branch.csv"
code: 0: <`"data/code.csv"
contact: 0: <`"data/contact.csv"
denomination: 0: <`"data/denomination.csv"
enterprise: 0: <`"data/enterprise.csv"
establishment: 0: <`"data/establishment.csv"
meta: 0: <`"data/meta.csv"
