const std = @import("std");
pub fn fourcc(comptime tag: []const u8) u32 {
  if (tag.len != 4) @panic("");
  return (@as(u32, tag[0])) | (@as(u32, tag[1]) <<  8) | (@as(u32, tag[2]) << 16) | (@as(u32, tag[3]) << 24);
}
pub fn BitFlags(comptime F: type) type {
  const A = std.meta.Int(.unsigned, @typeInfo(F).Enum.fields.len);
  return struct {
    a: A = 0, const B = @This();
    pub fn empty() B { return .{ .a = 0 }; }
    pub fn full() B { return .{ .a = ~@as(A, 0) }; }
    pub fn set(b: *B, f: F) void { b.a |= mask(f); }
    pub fn unset(b: *B, f: F) void { b.a &= ~mask(f); }
    pub fn toggle(b: *B, f: F) void { b.a ^= mask(f); }
    pub fn has(b: B, f: F) bool { return (b.a & mask(f)) != 0; }
    pub fn clear(b: *B) void { b.a = 0; }
    pub fn toInt(b: B) A { return b.a; }
    pub fn fromInt(v: A) B { return .{ .a = v }; }
    fn mask(f: F) A { return @as(A, 1) << @intFromEnum(f); }
  };
}
pub const BreakFlags = struct {
  pub const direction = 1 << 0;
  pub const script = 1 << 1;
  pub const grapheme = 1 << 2;
  pub const word = 1 << 3;
  pub const line_soft = 1 << 4;
  pub const line_hard = 1 << 5;
  pub const manual = 1 << 6;
  pub const paragraph_direction = 1 << 7;
  pub const line = line_soft | line_hard;
  pub const any = direction | script | grapheme | word | line_soft | line_hard;
};
/// Japanese text contains "kinsoku" characters, around which breaking a line is forbidden.
pub const JapaneseLineBreak = enum(u8) { strict, normal, loose };
pub const BreakStateFlags = struct {
  pub const started = 1;
  pub const end = 2;
  pub const saw_r_after_l = 8;
  pub const saw_al_after_lr = 0x10;
  pub const last_was_bracket = 0x20;
};
pub const TextFormat = enum(u32) { none, utf32, utf8 };
pub const Direction = enum(u32) { dont_know, ltr, rtl };
pub const Orientation = enum(u32) { horizontal, vertical };
pub const ShapingTable = enum(u8) { gsub, gpos };
pub const ShapeError = enum(u32) { none, invalid_font, gave_text_before_calling_begin, out_of_memory };
pub const AllocatorOpKind = enum(u32) { none, allocate, free };
pub const BlobTableId = enum(u32) { none, head, cmap, gdef, gsub, gpos, hhea, vhea, hmtx, vmtx, maxp, os2, name };
pub const LoadFontError = enum(u32) { none, need_to_create_blob, invalid_font, out_of_memory, file_error, read_error };
pub const Version = enum(u32) { v1_x, v2_0, pub const current = Version.v2_0; };
pub const BlobVersion = enum(u32) {
  invalid,
  initial,
  removed_subtable_infos_aligned_tables,
  pub const current = .removed_subtable_infos_aligned_tables;
};
pub const FontStyleFlags = BitFlags(enum{none, regular, italic, bold});
pub const FontWeight = enum(u32) {
  unknown,
  xxs, xs, s,
  ms, m, ml,
  l, xl, xxl,
};
pub const FontWidth = enum(u32) {
  unknown,
  xxs, xs, s,
  ms, m, ml,
  l, xl, xxl,
};
pub const GlyphFlags = BitFlags(enum {
  isol, fina, fin2, fin3, medi, med2, init, ljmo, vjmo, tjmo,
  rphf, blwf, half, pstf, abvf, pref, numr, frac, dnom, cfar,
  do_not_decompose, first_in_multiple_substitution, no_break,
  cursive, generated_by_gsub, used_in_gpos, stch_endpoint,
  stch_extension, ligature, multiple_substitution,
});
pub const JoiningFeature = enum(u8) { none, isol, fina, fin2, fin3, medi, med2, init };
pub const UserIdGenerationMode = enum(u32) { codepoint_index, source_index };
pub const BreakConfigFlags = struct {
  pub const none = 0;
  pub const end_of_text_generates_hard_line_break = 1;
};
pub const FontInfoStringId = enum(u32) {
  none, copyright, family, subfamily, uid, full_name, version,
  postscript_name, trademark, manufacturer, designer,
  typographic_family, typographic_subfamily,
};
pub const UnicodeJoiningType = enum(u8) { none, left, dual, force, right, transparent };
pub const UnicodeFlags = struct {
  pub const modifier_combining_mark = 1 << 0;
  pub const default_ignorable = 1 << 1;
  pub const open_bracket = 1 << 2;
  pub const close_bracket = 1 << 3;
  pub const part_of_word = 1 << 4;
  pub const decimal_digit = 1 << 5;
  pub const non_spacing_mark = 1 << 6;
  pub const mirrored = open_bracket | close_bracket;
};
/// Ignore Formatting characters except for ni
pub const UnicodeBidirectionalClass = enum(u8) { ni, bn, l, r, nsm, al, an, en, es, et, cs };

pub const LineBreakClass = enum(u8) {
  onea = 0,
  oea = 1,
  ope = 2,
  bk = 3,
  cr = 4,
  lf = 5,
  nl = 6,
  sp = 7,
  zw = 8,
  wj = 9,
  glnea = 10,
  glea = 11,
  clnea = 12,
  clea = 13,
  cpnea = 14,
  cpea = 15,
  exnea = 16,
  exea = 17,
  sy = 18,
  banea = 19,
  baea = 20,
  opnea = 21,
  opea = 22,
  qu = 23,
  qupi = 24,
  qupf = 25,
  is = 26,
  nsnea = 27,
  nsea = 28,
  b2 = 29,
  cb = 30,
  hy = 31,
  hyphen = 32,
  innea = 33,
  inea = 34,
  bb = 35,
  hl = 36,
  alnea = 37,
  alea = 38,
  nu = 39,
  prnea = 40,
  prea = 41,
  idnea = 42,
  idea = 43,
  idpe = 44,
  ebnea = 45,
  ebea = 46,
  em = 47,
  ponea = 48,
  poea = 49,
  jl = 50,
  jv = 51,
  jt = 52,
  h2 = 53,
  h3 = 54,
  ap = 55,
  ak = 56,
  dotted_circle = 57,
  as = 58,
  vf = 59,
  vi = 60,
  ri = 61,
  cm = 63,
  zwj = 64,
  cj = 65,
  sot = 66,
  eot = 67,
};

pub const WordBreakClass = enum(u8) {
  onep, oep, cr, lf, nl, ex, zwj, ri,
  fo, ka, hl, alnep, alep, sq, dq, mnl,
  ml, mn, nm, enl, wss, sot,
};

pub const Shaper = enum(u32) {
  default, arabic, hangul,
  hebrew, indic, khmer,
  myanmar, tibetan, use,
};

pub const maximum_recomposition_parents = 19;
pub const maximum_codepoint_scripts = 23;

pub const ScriptTag = enum(u32) {
  dont_know = fourcc("    "),
  adlam = fourcc("adlm"),
  ahom = fourcc("ahom"),
  anatolian_hieroglyphs = fourcc("hluw"),
  arabic = fourcc("arab"),
  armenian = fourcc("armn"),
  avestan = fourcc("avst"),
  balinese = fourcc("bali"),
  bamum = fourcc("bamu"),
  bassa_vah = fourcc("bass"),
  batak = fourcc("batk"),
  bengali = fourcc("bng2"),
  bhaiksuki = fourcc("bhks"),
  bopomofo = fourcc("bopo"),
  brahmi = fourcc("brah"),
  buginese = fourcc("bugi"),
  buhid = fourcc("buhd"),
  canadian_syllabics = fourcc("cans"),
  carian = fourcc("cari"),
  caucasian_albanian = fourcc("aghb"),
  chakma = fourcc("cakm"),
  cham = fourcc("cham"),
  cherokee = fourcc("cher"),
  chorasmian = fourcc("chrs"),
  cjk_ideographic = fourcc("hani"),
  coptic = fourcc("copt"),
  cypriot_syllabary = fourcc("cprt"),
  cypro_minoan = fourcc("cpmn"),
  cyrillic = fourcc("cyrl"),
  default = fourcc("DFLT"),
  default2 = fourcc("DFLT"),
  deseret = fourcc("dsrt"),
  devanagari = fourcc("dev2"),
  dives_akuru = fourcc("diak"),
  dogra = fourcc("dogr"),
  duployan = fourcc("dupl"),
  egyptian_hieroglyphs = fourcc("egyp"),
  elbasan = fourcc("elba"),
  elymaic = fourcc("elym"),
  ethiopic = fourcc("ethi"),
  garay = fourcc("gara"),
  georgian = fourcc("geor"),
  glagolitic = fourcc("glag"),
  gothic = fourcc("goth"),
  grantha = fourcc("gran"),
  greek = fourcc("grek"),
  gujarati = fourcc("gjr2"),
  gunjala_gondi = fourcc("gong"),
  gurmukhi = fourcc("gur2"),
  gurung_khema = fourcc("gukh"),
  hangul = fourcc("hang"),
  hanifi_rohingya = fourcc("rohg"),
  hanunoo = fourcc("hano"),
  hatran = fourcc("hatr"),
  hebrew = fourcc("hebr"),
  hiragana = fourcc("kana"),
  imperial_aramaic = fourcc("armi"),
  inscriptional_pahlavi = fourcc("phli"),
  inscriptional_parthian = fourcc("prti"),
  javanese = fourcc("java"),
  kaithi = fourcc("kthi"),
  kannada = fourcc("knd2"),
  katakana = @intFromEnum(Script.hiragana),
  kawi = fourcc("kawi"),
  kayah_li = fourcc("kali"),
  kharoshthi = fourcc("khar"),
  khitan_small_script = fourcc("kits"),
  khmer = fourcc("khmr"),
  khojki = fourcc("khoj"),
  khudawadi = fourcc("sind"),
  kirat_rai = fourcc("krai"),
  lao = fourcc("lao "),
  latin = fourcc("latn"),
  lepcha = fourcc("lepc"),
  limbu = fourcc("limb"),
  linear_a = fourcc("lina"),
  linear_b = fourcc("linb"),
  lisu = fourcc("lisu"),
  lycian = fourcc("lyci"),
  lydian = fourcc("lydi"),
  mahajani = fourcc("mahj"),
  makasar = fourcc("maka"),
  malayalam = fourcc("mlm2"),
  mandaic = fourcc("mand"),
  manichaean = fourcc("mani"),
  marchen = fourcc("marc"),
  masaram_gondi = fourcc("gonm"),
  medefaidrin = fourcc("medf"),
  meetei_mayek = fourcc("mtei"),
  mende_kikakui = fourcc("mend"),
  meroitic_cursive = fourcc("merc"),
  meroitic_hieroglyphs = fourcc("mero"),
  miao = fourcc("plrd"),
  modi = fourcc("modi"),
  mongolian = fourcc("mong"),
  mro = fourcc("mroo"),
  multani = fourcc("mult"),
  myanmar = fourcc("mym2"),
  nabataean = fourcc("nbat"),
  nag_mundari = fourcc("nagm"),
  nandinagari = fourcc("nand"),
  newa = fourcc("newa"),
  new_tai_lue = fourcc("talu"),
  nko = fourcc("nko "),
  nushu = fourcc("nshu"),
  nyiakeng_puachue_hmong = fourcc("hmnp"),
  ogham = fourcc("ogam"),
  ol_chiki = fourcc("olck"),
  ol_onal = fourcc("onao"),
  old_italic = fourcc("ital"),
  old_hungarian = fourcc("hung"),
  old_north_arabian = fourcc("narb"),
  old_permic = fourcc("perm"),
  old_persian_cuneiform = fourcc("xpeo"),
  old_sogdian = fourcc("sogo"),
  old_south_arabian = fourcc("sarb"),
  old_turkic = fourcc("orkh"),
  old_uyghur = fourcc("ougr"),
  odia = fourcc("ory2"),
  osage = fourcc("osge"),
  osmanya = fourcc("osma"),
  pahawh_hmong = fourcc("hmng"),
  palmyrene = fourcc("palm"),
  pau_cin_hau = fourcc("pauc"),
  phags_pa = fourcc("phag"),
  phoenician = fourcc("phnx"),
  psalter_pahlavi = fourcc("phlp"),
  rejang = fourcc("rjng"),
  runic = fourcc("runr"),
  samaritan = fourcc("samr"),
  saurashtra = fourcc("saur"),
  sharada = fourcc("shrd"),
  shavian = fourcc("shaw"),
  siddham = fourcc("sidd"),
  sign_writing = fourcc("sgnw"),
  sogdian = fourcc("sogd"),
  sinhala = fourcc("sinh"),
  sora_sompeng = fourcc("sora"),
  soyombo = fourcc("soyo"),
  sumero_akkadian_cuneiform = fourcc("xsux"),
  sundanese = fourcc("sund"),
  sunuwar = fourcc("sunu"),
  syloti_nagri = fourcc("sylo"),
  syriac = fourcc("syrc"),
  tagalog = fourcc("tglg"),
  tagbanwa = fourcc("tagb"),
  tai_le = fourcc("tale"),
  tai_tham = fourcc("lana"),
  tai_viet = fourcc("tavt"),
  takri = fourcc("takr"),
  tamil = fourcc("tml2"),
  tangsa = fourcc("tnsa"),
  tangut = fourcc("tang"),
  telugu = fourcc("tel2"),
  thaana = fourcc("thaa"),
  thai = fourcc("thai"),
  tibetan = fourcc("tibt"),
  tifinagh = fourcc("tfng"),
  tirhuta = fourcc("tirh"),
  todhri = fourcc("todr"),
  toto = fourcc("toto"),
  tulu_tigalari = fourcc("tutg"),
  ugaritic_cuneiform = fourcc("ugar"),
  vai = fourcc("vai "),
  vithkuqi = fourcc("vith"),
  wancho = fourcc("wcho"),
  warang_citi = fourcc("wara"),
  yezidi = fourcc("yezi"),
  yi = fourcc("yi  "),
  zanabazar_square = fourcc("zanb"),
};

pub const Script = enum(u32) {
  dont_know,
  adlam,
  ahom,
  anatolian_hieroglyphs,
  arabic,
  armenian,
  avestan,
  balinese,
  bamum,
  bassa_vah,
  batak,
  bengali,
  bhaiksuki,
  bopomofo,
  brahmi,
  buginese,
  buhid,
  canadian_syllabics,
  carian,
  caucasian_albanian,
  chakma,
  cham,
  cherokee,
  chorasmian,
  cjk_ideographic,
  coptic,
  cypriot_syllabary,
  cypro_minoan,
  cyrillic,
  default,
  default2,
  deseret,
  devanagari,
  dives_akuru,
  dogra,
  duployan,
  egyptian_hieroglyphs,
  elbasan,
  elymaic,
  ethiopic,
  garay,
  georgian,
  glagolitic,
  gothic,
  grantha,
  greek,
  gujarati,
  gunjala_gondi,
  gurmukhi,
  gurung_khema,
  hangul,
  hanifi_rohingya,
  hanunoo,
  hatran,
  hebrew,
  hiragana,
  imperial_aramaic,
  inscriptional_pahlavi,
  inscriptional_parthian,
  javanese,
  kaithi,
  kannada,
  katakana,
  kawi,
  kayah_li,
  kharoshthi,
  khitan_small_script,
  khmer,
  khojki,
  khudawadi,
  kirat_rai,
  lao,
  latin,
  lepcha,
  limbu,
  linear_a,
  linear_b,
  lisu,
  lycian,
  lydian,
  mahajani,
  makasar,
  malayalam,
  mandaic,
  manichaean,
  marchen,
  masaram_gondi,
  medefaidrin,
  meetei_mayek,
  mende_kikakui,
  meroitic_cursive,
  meroitic_hieroglyphs,
  miao,
  modi,
  mongolian,
  mro,
  multani,
  myanmar,
  nabataean,
  nag_mundari,
  nandinagari,
  newa,
  new_tai_lue,
  nko,
  nushu,
  nyiakeng_puachue_hmong,
  ogham,
  ol_chiki,
  ol_onal,
  old_italic,
  old_hungarian,
  old_north_arabian,
  old_permic,
  old_persian_cuneiform,
  old_sogdian,
  old_south_arabian,
  old_turkic,
  old_uyghur,
  odia,
  osage,
  osmanya,
  pahawh_hmong,
  palmyrene,
  pau_cin_hau,
  phags_pa,
  phoenician,
  psalter_pahlavi,
  rejang,
  runic,
  samaritan,
  saurashtra,
  sharada,
  shavian,
  siddham,
  sign_writing,
  sogdian,
  sinhala,
  sora_sompeng,
  soyombo,
  sumero_akkadian_cuneiform,
  sundanese,
  sunuwar,
  syloti_nagri,
  syriac,
  tagalog,
  tagbanwa,
  tai_le,
  tai_tham,
  tai_viet,
  takri,
  tamil,
  tangsa,
  tangut,
  telugu,
  thaana,
  thai,
  tibetan,
  tifinagh,
  tirhuta,
  todhri,
  toto,
  tulu_tigalari,
  ugaritic_cuneiform,
  vai,
  vithkuqi,
  wancho,
  warang_citi,
  yezidi,
  yi,
  zanabazar_square,
};

pub const FeatureTag = enum(u32) {
  unregistered = fourcc("\x00\x00\x00\x00"),
  isol = fourcc("isol"),
  fina = fourcc("fina"),
  fin2 = fourcc("fin2"),
  fin3 = fourcc("fin3"),
  medi = fourcc("medi"),
  med2 = fourcc("med2"),
  init = fourcc("init"),
  ljmo = fourcc("ljmo"),
  vjmo = fourcc("vjmo"),
  tjmo = fourcc("tjmo"),
  rphf = fourcc("rphf"),
  blwf = fourcc("blwf"),
  half = fourcc("half"),
  pstf = fourcc("pstf"),
  abvf = fourcc("abvf"),
  pref = fourcc("pref"),
  numr = fourcc("numr"),
  frac = fourcc("frac"),
  dnom = fourcc("dnom"),
  cfar = fourcc("cfar"),
  aalt = fourcc("aalt"),
  abvm = fourcc("abvm"),
  abvs = fourcc("abvs"),
  afrc = fourcc("afrc"),
  akhn = fourcc("akhn"),
  apkn = fourcc("apkn"),
  blwm = fourcc("blwm"),
  blws = fourcc("blws"),
  calt = fourcc("calt"),
  case = fourcc("case"),
  ccmp = fourcc("ccmp"),
  chws = fourcc("chws"),
  cjct = fourcc("cjct"),
  clig = fourcc("clig"),
  cpct = fourcc("cpct"),
  cpsp = fourcc("cpsp"),
  cswh = fourcc("cswh"),
  curs = fourcc("curs"),
  cv01 = fourcc("cv01"),
  cv02 = fourcc("cv02"),
  cv03 = fourcc("cv03"),
  cv04 = fourcc("cv04"),
  cv05 = fourcc("cv05"),
  cv06 = fourcc("cv06"),
  cv07 = fourcc("cv07"),
  cv08 = fourcc("cv08"),
  cv09 = fourcc("cv09"),
  cv10 = fourcc("cv10"),
  cv11 = fourcc("cv11"),
  cv12 = fourcc("cv12"),
  cv13 = fourcc("cv13"),
  cv14 = fourcc("cv14"),
  cv15 = fourcc("cv15"),
  cv16 = fourcc("cv16"),
  cv17 = fourcc("cv17"),
  cv18 = fourcc("cv18"),
  cv19 = fourcc("cv19"),
  cv20 = fourcc("cv20"),
  cv21 = fourcc("cv21"),
  cv22 = fourcc("cv22"),
  cv23 = fourcc("cv23"),
  cv24 = fourcc("cv24"),
  cv25 = fourcc("cv25"),
  cv26 = fourcc("cv26"),
  cv27 = fourcc("cv27"),
  cv28 = fourcc("cv28"),
  cv29 = fourcc("cv29"),
  cv30 = fourcc("cv30"),
  cv31 = fourcc("cv31"),
  cv32 = fourcc("cv32"),
  cv33 = fourcc("cv33"),
  cv34 = fourcc("cv34"),
  cv35 = fourcc("cv35"),
  cv36 = fourcc("cv36"),
  cv37 = fourcc("cv37"),
  cv38 = fourcc("cv38"),
  cv39 = fourcc("cv39"),
  cv40 = fourcc("cv40"),
  cv41 = fourcc("cv41"),
  cv42 = fourcc("cv42"),
  cv43 = fourcc("cv43"),
  cv44 = fourcc("cv44"),
  cv45 = fourcc("cv45"),
  cv46 = fourcc("cv46"),
  cv47 = fourcc("cv47"),
  cv48 = fourcc("cv48"),
  cv49 = fourcc("cv49"),
  cv50 = fourcc("cv50"),
  cv51 = fourcc("cv51"),
  cv52 = fourcc("cv52"),
  cv53 = fourcc("cv53"),
  cv54 = fourcc("cv54"),
  cv55 = fourcc("cv55"),
  cv56 = fourcc("cv56"),
  cv57 = fourcc("cv57"),
  cv58 = fourcc("cv58"),
  cv59 = fourcc("cv59"),
  cv60 = fourcc("cv60"),
  cv61 = fourcc("cv61"),
  cv62 = fourcc("cv62"),
  cv63 = fourcc("cv63"),
  cv64 = fourcc("cv64"),
  cv65 = fourcc("cv65"),
  cv66 = fourcc("cv66"),
  cv67 = fourcc("cv67"),
  cv68 = fourcc("cv68"),
  cv69 = fourcc("cv69"),
  cv70 = fourcc("cv70"),
  cv71 = fourcc("cv71"),
  cv72 = fourcc("cv72"),
  cv73 = fourcc("cv73"),
  cv74 = fourcc("cv74"),
  cv75 = fourcc("cv75"),
  cv76 = fourcc("cv76"),
  cv77 = fourcc("cv77"),
  cv78 = fourcc("cv78"),
  cv79 = fourcc("cv79"),
  cv80 = fourcc("cv80"),
  cv81 = fourcc("cv81"),
  cv82 = fourcc("cv82"),
  cv83 = fourcc("cv83"),
  cv84 = fourcc("cv84"),
  cv85 = fourcc("cv85"),
  cv86 = fourcc("cv86"),
  cv87 = fourcc("cv87"),
  cv88 = fourcc("cv88"),
  cv89 = fourcc("cv89"),
  cv90 = fourcc("cv90"),
  cv91 = fourcc("cv91"),
  cv92 = fourcc("cv92"),
  cv93 = fourcc("cv93"),
  cv94 = fourcc("cv94"),
  cv95 = fourcc("cv95"),
  cv96 = fourcc("cv96"),
  cv97 = fourcc("cv97"),
  cv98 = fourcc("cv98"),
  cv99 = fourcc("cv99"),
  c2pc = fourcc("c2pc"),
  c2sc = fourcc("c2sc"),
  dist = fourcc("dist"),
  dlig = fourcc("dlig"),
  dtls = fourcc("dtls"),
  expt = fourcc("expt"),
  falt = fourcc("falt"),
  flac = fourcc("flac"),
  fwid = fourcc("fwid"),
  haln = fourcc("haln"),
  halt = fourcc("halt"),
  hist = fourcc("hist"),
  hkna = fourcc("hkna"),
  hlig = fourcc("hlig"),
  hngl = fourcc("hngl"),
  hojo = fourcc("hojo"),
  hwid = fourcc("hwid"),
  ital = fourcc("ital"),
  jalt = fourcc("jalt"),
  jp78 = fourcc("jp78"),
  jp83 = fourcc("jp83"),
  jp90 = fourcc("jp90"),
  jp04 = fourcc("jp04"),
  kern = fourcc("kern"),
  lfbd = fourcc("lfbd"),
  liga = fourcc("liga"),
  lnum = fourcc("lnum"),
  locl = fourcc("locl"),
  ltra = fourcc("ltra"),
  ltrm = fourcc("ltrm"),
  mark = fourcc("mark"),
  mgrk = fourcc("mgrk"),
  mkmk = fourcc("mkmk"),
  mset = fourcc("mset"),
  nalt = fourcc("nalt"),
  nlck = fourcc("nlck"),
  nukt = fourcc("nukt"),
  onum = fourcc("onum"),
  opbd = fourcc("opbd"),
  ordn = fourcc("ordn"),
  ornm = fourcc("ornm"),
  palt = fourcc("palt"),
  pcap = fourcc("pcap"),
  pkna = fourcc("pkna"),
  pnum = fourcc("pnum"),
  pres = fourcc("pres"),
  psts = fourcc("psts"),
  pwid = fourcc("pwid"),
  qwid = fourcc("qwid"),
  rand = fourcc("rand"),
  rclt = fourcc("rclt"),
  rkrf = fourcc("rkrf"),
  rlig = fourcc("rlig"),
  rtbd = fourcc("rtbd"),
  rtla = fourcc("rtla"),
  rtlm = fourcc("rtlm"),
  ruby = fourcc("ruby"),
  rvrn = fourcc("rvrn"),
  salt = fourcc("salt"),
  sinf = fourcc("sinf"),
  size = fourcc("size"),
  smcp = fourcc("smcp"),
  smpl = fourcc("smpl"),
  ss01 = fourcc("ss01"),
  ss02 = fourcc("ss02"),
  ss03 = fourcc("ss03"),
  ss04 = fourcc("ss04"),
  ss05 = fourcc("ss05"),
  ss06 = fourcc("ss06"),
  ss07 = fourcc("ss07"),
  ss08 = fourcc("ss08"),
  ss09 = fourcc("ss09"),
  ss10 = fourcc("ss10"),
  ss11 = fourcc("ss11"),
  ss12 = fourcc("ss12"),
  ss13 = fourcc("ss13"),
  ss14 = fourcc("ss14"),
  ss15 = fourcc("ss15"),
  ss16 = fourcc("ss16"),
  ss17 = fourcc("ss17"),
  ss18 = fourcc("ss18"),
  ss19 = fourcc("ss19"),
  ss20 = fourcc("ss20"),
  ssty = fourcc("ssty"),
  stch = fourcc("stch"),
  subs = fourcc("subs"),
  sups = fourcc("sups"),
  swsh = fourcc("swsh"),
  @"test" = fourcc("test"),
  titl = fourcc("titl"),
  tnam = fourcc("tnam"),
  tnum = fourcc("tnum"),
  trad = fourcc("trad"),
  twid = fourcc("twid"),
  unic = fourcc("unic"),
  valt = fourcc("valt"),
  vapk = fourcc("vapk"),
  vatu = fourcc("vatu"),
  vchw = fourcc("vchw"),
  vert = fourcc("vert"),
  vhal = fourcc("vhal"),
  vkna = fourcc("vkna"),
  vkrn = fourcc("vkrn"),
  vpal = fourcc("vpal"),
  vrt2 = fourcc("vrt2"),
  vrtr = fourcc("vrtr"),
  zero = fourcc("zero"),
};
pub const AllocatorOpAllocate = struct { pointer: ?*anyopaque, size: u32 };
pub const AllocatorOpFree = struct { pointer: ?*anyopaque };
pub const AllocatorOp = union(AllocatorOpKind) {
  none: void,
  allocate: AllocatorOpAllocate,
  free: AllocatorOpFree,
};
pub const AllocatorFn = *const fn (data: ?*anyopaque, op: *AllocatorOp) void;
pub const BlobTable = struct { offset_from_start_of_file: u32, length: u32 };
pub const LoadFontState = struct {
  font_data: ?*anyopaque,
  font_data_size: u32,
  tables: [13]BlobTable,
  lookup_count: u32,
  lookup_subtable_count: u32,
  glyph_count: u32,
  scratch_size: u32,
  glyph_lookup_matrix_size_in_bytes: u32,
  glyph_lookup_subtable_matrix_size_in_bytes: u32,
  total_size: u32,
};

pub const BlobHeader = struct {
  magic: u32,
  version: u32,
  lookup_count: u32,
  lookup_subtable_count: u32,
  glyph_count: u32,
  gpos_lookup_index_offset: u32,
  glyph_lookup_matrix_offset_from_start_of_file: u32,
  glyph_lookup_subtable_matrix_offset_from_start_of_file: u32,
  lookup_subtable_index_offsets_offset_from_start_of_file: u32,
  subtable_infos_offset_from_start_of_file: u32,
  tables: [13]BlobTable,
};

pub const Cmap14 = opaque {};
pub const GsubGpos = opaque {};

pub const Font = struct {
  allocator: ?AllocatorFn,
  allocator_data: ?*anyopaque,
  blob: ?*BlobHeader,
  cmap: ?[*]u16,
  cmap14: ?*Cmap14,
  shaping_tables: [2]?*GsubGpos,
  user_data: ?*anyopaque,
  err: LoadFontError,
};
pub const FontInfo = struct {
  strings: [13]?[*:0]const u8,
  string_lengths: [13]u16,
  style_flags: u32,
  weight: FontWeight,
  width: FontWidth,
};
pub const FontInfo2 = struct {
  size: u32,
  strings: [13]?[*:0]const u8,
  string_lengths: [13]u16,
  style_flags: u32,
  weight: FontWeight,
  width: FontWidth,
};
pub const FontInfo2_1 = struct {
  base: FontInfo2, units_per_em: u16,
  x_min: i16, y_min: i16, x_max: i16, y_max: i16,
  ascent: i16, descent: i16, line_gap: i16,
};
pub const FontInfo2_2 = struct {
  base: FontInfo2, units_per_em: u16,
  x_min: i16, y_min: i16, x_max: i16, y_max: i16,
  ascent: i16, descent: i16, line_gap: i16, capital_height: i16,
};
pub const FeatureOverride = struct { tag: FeatureTag, value: i32 };

pub const Break = struct {
  position: i32,
  flags: u32,
  direction: Direction,
  paragraph_direction: Direction,
  script: Script,
};

pub const Bracket = struct { codepoint: u32, position: u32, direction: u8, script: u8 };

pub const BreakState = struct {
  breaks: [8]Break,
  break_count: u32,
  paragraph_direction: Direction,
  user_paragraph_direction: Direction,
  current_position: u32,
  paragraph_start_position: u32,
  last_script_break_position: u32,
  last_direction_break_position: u32,
  last_script_break_script: u8,
  last_direction_break_direction: u8,
  script_position_offset: i16,
  script_count: u32,
  script_set: [maximum_codepoint_scripts]u8,
  brackets: [64]Bracket,
  bracket_count: u32,
  flags: u32,
  flag_state: u32,
  position_offset2: i16,
  position_offset3: i16,
  word_break_history: u32,
  word_breaks: u16,
  word_unbreaks: u16,
  word_break2_position_offset: i16,
  line_breaks: u64,
  line_unbreaks_async: u64,
  line_unbreaks: u64,
  line_break_history: u32,
  line_break2_position_offset: i16,
  line_break3_position_offset: i16,
  last_direction: u8,
  bidirectional_class2: u8,
  bidirectional_class1: u8,
  bidirectional1_position_offset: i16,
  bidirectional2_position_offset: i16,
  japanese_line_break_style: JapaneseLineBreak,
  config_flags: u32,
  grapheme_break_state: u8,
  last_line_break_class: u8,
  last_word_break_class: u8,
  last_word_break_class_including_ignored: u8,
};
pub const Decode = struct { codepoint: i32, source_characters_consumed: i32, valid: bool };
pub const EncodeUtf8 = struct { encoded: [4]u8, encoded_length: i32, valid: bool };
pub const GlyphClasses = struct { class: u16, mark_attachment_class: u16 };
pub const GlyphConfig = opaque {};
pub const BucketedGlyph = opaque {};
pub const Glyph = struct {
  prev: ?*Glyph, next: ?*Glyph,
  codepoint: u32, id: u16, uid: u16,
  user_id_or_codepoint_index: i32,
  offset_x: i32, offset_y: i32,
  advance_x: i32, advance_y: i32,
  attach_glyph: ?*Glyph,
  config: ?*GlyphConfig,
  decomposition: u64,
  classes: GlyphClasses, flags: u32, parent_info: u32,
  bucketed: ?*BucketedGlyph, sort_key: u32, sort_key_interval: u32,
  bucketed_bucket_index: u16, ligature_uid: u16,
  ligature_component_index_plus_one: u16, ligature_component_count: u16,
  joining_feature: JoiningFeature, joining_type: UnicodeJoiningType,
  unicode_flags: u8, syllabic_class: u8, syllabic_position: u8,
  use_class: u8, combining_class: u8, mark_ordering: u8,
};

pub const ShapeCodepoint = struct {
  font: ?*Font,
  feature_overrides: ?[*]FeatureOverride,
  feature_override_count: i32,
  codepoint: i32,
  user_id: i32,
  break_flags: u32,
  script: Script,
  direction: Direction,
  paragraph_direction: Direction,
};

pub const ShapeContext = opaque {};

pub const ShapeCodepointIterator = struct {
  codepoint: ?*ShapeCodepoint,
  context: ?*ShapeContext,
  end_block_index: u32,
  one_past_last_codepoint_index: u32,
  block_index: u32,
  codepoint_index: u32,
  current_block_codepoint_count: u32,
  flat_codepoint_index: u32,
};

pub const GlyphIterator = struct {
  glyph_storage: ?*GlyphStorage,
  current_glyph: ?*Glyph,
  last_advance_x: i32,
  x: i32,
  y: i32,
};

pub const ArenaBlockHeader = struct {
  prev: ?*ArenaBlockHeader,
  next: ?*ArenaBlockHeader,
};

pub const Arena = struct {
  allocator: ?AllocatorFn,
  allocator_data: ?*anyopaque,
  block_sentinel: ArenaBlockHeader,
  free_block_sentinel: ArenaBlockHeader,
  err: i32,
};

pub const GlyphStorage = struct {
  arena: Arena,
  glyph_sentinel: Glyph,
  free_glyph_sentinel: Glyph,
  err: i32,
};
pub const GlyphParent = struct { codepoint: u32, codepoint1: u32 };
pub const FontCoverageTest = struct {
  font: ?*Font,
  base_codepoint: u32,
  current_base_error: i32,
  err: i32,
  base_parents: [maximum_recomposition_parents]GlyphParent,
  base_parent_count: u32,
};
pub const Run = struct {
  font: ?*Font,
  script: Script,
  paragraph_direction: Direction,
  direction: Direction,
  flags: u32,
  glyphs: GlyphIterator,
};
pub const ShapeConfig = opaque {};
pub const ShapeScratchpad = opaque {};
pub const RephPosition = enum(u8) { after_post, before_post, before_subjoined, after_subjoined, after_main };
pub const RephEncoding = enum(u8) { implicit, explicit, logical_repha, visual_repha };
pub const SyllabicPosition = enum(u8) {
  none,
  ra_to_become_reph,
  prebase_matra,
  prebase_consonant,
  syllable_base,
  after_main,
  abovebase_consonant,
  before_subjoined,
  belowbase_consonant,
  after_subjoined,
  before_post,
  postbase_consonant,
  after_post,
  final_consonant,
  smvd,
};
pub const FeatureId = enum(u32) {
  unregistered, isol, fina, fin2, fin3, medi, med2, init,
  ljmo, vjmo, tjmo, rphf, blwf, half, pstf, abvf, pref, numr, frac,
  dnom, cfar, aalt, abvm, abvs, afrc, akhn, apkn, blwm, blws, calt, case,
  ccmp, chws, cjct, clig, cpct, cpsp, cswh, curs,
  cv01, cv02, cv03, cv04, cv05, cv06, cv07, cv08, cv09, cv10,
  cv11, cv12, cv13, cv14, cv15, cv16, cv17, cv18, cv19, cv20,
  cv21, cv22, cv23, cv24, cv25, cv26, cv27, cv28, cv29, cv30,
  cv31, cv32, cv33, cv34, cv35, cv36, cv37, cv38, cv39, cv40,
  cv41, cv42, cv43, cv44, cv45, cv46, cv47, cv48, cv49, cv50,
  cv51, cv52, cv53, cv54, cv55, cv56, cv57, cv58, cv59, cv60,
  cv61, cv62, cv63, cv64, cv65, cv66, cv67, cv68, cv69, cv70,
  cv71, cv72, cv73, cv74, cv75, cv76, cv77, cv78, cv79, cv80,
  cv81, cv82, cv83, cv84, cv85, cv86, cv87, cv88, cv89, cv90,
  cv91, cv92, cv93, cv94, cv95, cv96, cv97, cv98, cv99,
  c2pc, c2sc, dist, dlig, dtls, expt, falt, flac, fwid, haln, halt, hist,
  hkna, hlig, hngl, hojo, hwid, ital, jalt, jp78, jp83, jp90, jp04, kern, lfbd,
  liga, lnum, locl, ltra, ltrm, mark, mgrk, mkmk, mset, nalt, nlck, nukt, onum,
  opbd, ordn, ornm, palt, pcap, pkna, pnum, pres, psts, pwid, qwid, rand, rclt,
  rkrf, rlig, rtbd, rtla, rtlm, ruby, rvrn, salt, sinf, size, smcp, smpl,
  ss01, ss02, ss03, ss04, ss05, ss06, ss07, ss08, ss09, ss10,
  ss11, ss12, ss13, ss14, ss15, ss16, ss17, ss18, ss19, ss20,
  ssty, stch, subs, sups, swsh, @"test", titl, tnam, tnum, trad, twid, unic,
  valt, vapk, vatu, vchw, vert, vhal, vkna, vkrn, vpal, vrt2, vrtr, zero,
  count,
};

pub const FeatureSet = struct {
  flags: [(@intFromEnum(FeatureId.count) + 63) / 64]u64,

  pub fn init(features: []const FeatureId) FeatureSet {
    var res = FeatureSet{ .flags = [_]u64{0} ** ((@intFromEnum(FeatureId.count) + 63) / 64) };
    for (features) |f| {
      const val = @intFromEnum(f);
      res.flags[val / 64] |= (@as(u64, 1) << @as(u6, @intCast(val % 64)));
    }
    return res;
  }
};

pub const OpKind = enum(u8) {
  end, pre_normalize_dotted_circles,
  normalize, normalize_hangul,
  flag_joining_letters,
  begin_gsub, gsub_features,
  gsub_features_with_user,
  gpos_metrics, gpos_features,
  post_gpos_fixup, stch_postpass,
  begin_cluster, end_cluster, end_syllable,
};

pub const FeatureStage = struct { feature_count: u32, features: FeatureSet };

pub const OpList = struct {
  total_feature_count: u32,
  feature_stage_count: u32,
  feature_stages: []const FeatureStage,
  op_count: u32,
  ops: []const OpKind,
};

pub const maximum_decomposition_codepoints = 6;
pub const ScriptProperties = struct { tag: u32, shaper: Shaper };
pub const ops_default = [_]OpKind{ .normalize, .begin_gsub, .gsub_features, .gsub_features_with_user, .gpos_metrics, .gpos_features, .post_gpos_fixup };
pub const feature_stages_default = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rvrn}) },
  .{ .feature_count = 19, .features = FeatureSet.init(&.{ .frac, .numr, .dnom, .ccmp, .clig, .calt, .abvm, .blwm, .curs, .ltra, .ltrm, .locl, .rlig, .liga, .rclt, .mark, .mkmk, .dist, .kern }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvm, .blwm, .curs, .mark, .mkmk, .dist, .kern }) },
};
pub const op_list_default = OpList{ .total_feature_count = 27, .feature_stage_count = feature_stages_default.len, .feature_stages = &feature_stages_default, .op_count = ops_default.len, .ops = &ops_default };
pub const ops_hangul = [_]OpKind{ .normalize, .normalize_hangul, .begin_gsub, .gsub_features, .gsub_features_with_user, .gpos_metrics, .gpos_features, .post_gpos_fixup };
pub const feature_stages_hangul = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rvrn}) },
  .{ .feature_count = 21, .features = FeatureSet.init(&.{ .frac, .numr, .dnom, .ljmo, .vjmo, .tjmo, .ccmp, .clig, .abvm, .blwm, .curs, .ltra, .ltrm, .rlig, .liga, .locl, .rclt, .mkmk, .mark, .dist, .kern }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvm, .blwm, .curs, .mkmk, .mark, .dist, .kern }) },
};
pub const op_list_hangul = OpList{ .total_feature_count = 29, .feature_stage_count = feature_stages_hangul.len, .feature_stages = &feature_stages_hangul, .op_count = ops_hangul.len, .ops = &ops_hangul };
pub const ops_arabic_rclt = [_]OpKind{ .normalize, .flag_joining_letters, .begin_gsub, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features_with_user, .gpos_metrics, .gpos_features, .stch_postpass, .post_gpos_fixup };
pub const feature_stages_arabic_rclt = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rvrn}) },
  .{ .feature_count = 5, .features = FeatureSet.init(&.{ .frac, .numr, .dnom, .rtla, .rtlm }) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.stch}) },
  .{ .feature_count = 2, .features = FeatureSet.init(&.{ .ccmp, .locl }) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.isol}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.fina}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.fin2}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.fin3}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.medi}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.med2}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.init}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rlig}) },
  .{ .feature_count = 12, .features = FeatureSet.init(&.{ .calt, .clig, .abvm, .blwm, .curs, .liga, .mset, .rclt, .mark, .mkmk, .dist, .kern }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvm, .blwm, .curs, .mark, .mkmk, .dist, .kern }) },
};
pub const op_list_arabic_rclt = OpList{ .total_feature_count = 36, .feature_stage_count = feature_stages_arabic_rclt.len, .feature_stages = &feature_stages_arabic_rclt, .op_count = ops_arabic_rclt.len, .ops = &ops_arabic_rclt };

pub const ops_arabic_no_rclt = [_]OpKind{ .normalize, .flag_joining_letters, .begin_gsub, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features_with_user, .gpos_metrics, .gpos_features, .stch_postpass, .post_gpos_fixup };
pub const feature_stages_arabic_no_rclt = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rvrn}) },
  .{ .feature_count = 5, .features = FeatureSet.init(&.{.frac, .numr, .dnom, .rtla, .rtlm}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.stch}) },
  .{ .feature_count = 2, .features = FeatureSet.init(&.{.ccmp, .locl}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.isol}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.fina}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.fin2}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.fin3}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.medi}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.med2}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.init}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rlig}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.calt}) },
  .{ .feature_count = 10, .features = FeatureSet.init(&.{ .clig, .abvm, .blwm, .curs, .liga, .mset, .mark, .mkmk, .dist, .kern }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvm, .blwm, .curs, .mark, .mkmk, .dist, .kern }) },
};
pub const op_list_arabic_no_rclt = OpList{ .total_feature_count = 35, .feature_stage_count = feature_stages_arabic_no_rclt.len, .feature_stages = &feature_stages_arabic_no_rclt, .op_count = ops_arabic_no_rclt.len, .ops = &ops_arabic_no_rclt };

pub const ops_indic = [_]OpKind{ .pre_normalize_dotted_circles, .normalize, .begin_gsub, .gsub_features, .gsub_features, .begin_cluster, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .end_cluster, .gsub_features, .end_syllable, .gsub_features_with_user, .gpos_metrics, .gpos_features, .post_gpos_fixup };
pub const feature_stages_indic = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rvrn}) },
  .{ .feature_count = 5, .features = FeatureSet.init(&.{ .frac, .numr, .dnom, .ltra, .ltrm }) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.nukt}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.akhn}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rphf}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rkrf}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.pref}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.blwf}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.abvf}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.half}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.pstf}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.vatu}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.cjct}) },
  .{ .feature_count = 6, .features = FeatureSet.init(&.{ .abvs, .blws, .init, .haln, .pres, .psts }) },
  .{ .feature_count = 12, .features = FeatureSet.init(&.{ .calt, .clig, .abvm, .blwm, .curs, .locl, .rlig, .rclt, .mark, .mkmk, .dist, .kern }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvm, .blwm, .curs, .mark, .mkmk, .dist, .kern }) },
};
pub const op_list_indic = OpList{ .total_feature_count = 42, .feature_stage_count = feature_stages_indic.len, .feature_stages = &feature_stages_indic, .op_count = ops_indic.len, .ops = &ops_indic };

pub const ops_khmer = [_]OpKind{ .pre_normalize_dotted_circles, .normalize, .begin_gsub, .gsub_features, .gsub_features, .begin_cluster, .gsub_features, .end_cluster, .end_syllable, .gsub_features_with_user, .gpos_metrics, .gpos_features, .post_gpos_fixup };
pub const feature_stages_khmer = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rvrn}) },
  .{ .feature_count = 5, .features = FeatureSet.init(&.{ .frac, .numr, .dnom, .ltra, .ltrm }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .ccmp, .pref, .blwf, .abvf, .pstf, .cfar, .locl }) },
  .{ .feature_count = 15, .features = FeatureSet.init(&.{ .abvs, .blws, .calt, .clig, .abvm, .blwm, .curs, .pres, .psts, .rclt, .rlig, .dist, .kern, .mark, .mkmk }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvm, .blwm, .curs, .dist, .kern, .mark, .mkmk }) },
};
pub const op_list_khmer = OpList{ .total_feature_count = 35, .feature_stage_count = feature_stages_khmer.len, .feature_stages = &feature_stages_khmer, .op_count = ops_khmer.len, .ops = &ops_khmer };

pub const ops_myanmar = [_]OpKind{ .pre_normalize_dotted_circles, .normalize, .begin_gsub, .gsub_features, .gsub_features, .begin_cluster, .gsub_features, .end_cluster, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .end_syllable, .gsub_features_with_user, .gpos_metrics, .gpos_features, .post_gpos_fixup };
pub const feature_stages_myanmar = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rvrn}) },
  .{ .feature_count = 5, .features = FeatureSet.init(&.{ .frac, .numr, .dnom, .ltra, .ltrm }) },
  .{ .feature_count = 2, .features = FeatureSet.init(&.{ .ccmp, .locl }) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rphf}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.pref}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.blwf}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.pstf}) },
  .{ .feature_count = 16, .features = FeatureSet.init(&.{ .abvs, .blws, .calt, .clig, .abvm, .blwm, .curs, .pres, .psts, .rlig, .liga, .rclt, .dist, .kern, .mark, .mkmk }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvm, .blwm, .curs, .dist, .kern, .mark, .mkmk }) },
};
pub const op_list_myanmar = OpList{ .total_feature_count = 35, .feature_stage_count = feature_stages_myanmar.len, .feature_stages = &feature_stages_myanmar, .op_count = ops_myanmar.len, .ops = &ops_myanmar };

pub const ops_tibetan = [_]OpKind{ .begin_gsub, .gsub_features, .gsub_features, .gsub_features_with_user, .gpos_metrics, .gpos_features, .post_gpos_fixup };
pub const feature_stages_tibetan = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.locl}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.ccmp}) },
  .{ .feature_count = 8, .features = FeatureSet.init(&.{ .abvs, .blws, .calt, .abvm, .blwm, .liga, .kern, .mkmk }) },
  .{ .feature_count = 4, .features = FeatureSet.init(&.{ .abvm, .blwm, .kern, .mkmk }) },
};
pub const op_list_tibetan = OpList{ .total_feature_count = 14, .feature_stage_count = feature_stages_tibetan.len, .feature_stages = &feature_stages_tibetan, .op_count = ops_tibetan.len, .ops = &ops_tibetan };

pub const ops_use = [_]OpKind{ .pre_normalize_dotted_circles, .normalize, .flag_joining_letters, .begin_gsub, .gsub_features, .gsub_features, .begin_cluster, .gsub_features, .gsub_features, .gsub_features, .gsub_features, .end_cluster, .end_syllable, .gsub_features, .gsub_features_with_user, .gpos_metrics, .gpos_features, .post_gpos_fixup };
pub const feature_stages_use = [_]FeatureStage{
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rvrn}) },
  .{ .feature_count = 5, .features = FeatureSet.init(&.{ .frac, .numr, .dnom, .ltra, .ltrm }) },
  .{ .feature_count = 4, .features = FeatureSet.init(&.{ .ccmp, .akhn, .locl, .nukt }) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.rphf}) },
  .{ .feature_count = 1, .features = FeatureSet.init(&.{.pref}) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvf, .blwf, .cjct, .half, .pstf, .rkrf, .vatu }) },
  .{ .feature_count = 4, .features = FeatureSet.init(&.{ .fina, .init, .isol, .medi }) },
  .{ .feature_count = 24, .features = FeatureSet.init(&.{ .abvs, .blws, .calt, .clig, .abvm, .blwm, .curs, .haln, .pres, .psts, .liga, .rclt, .rlig, .dist, .kern, .mark, .mkmk }) },
  .{ .feature_count = 7, .features = FeatureSet.init(&.{ .abvm, .blwm, .curs, .dist, .kern, .mark, .mkmk }) },
};
pub const op_list_use = OpList{ .total_feature_count = 54, .feature_stage_count = feature_stages_use.len, .feature_stages = &feature_stages_use, .op_count = ops_use.len, .ops = &ops_use };

pub const script_properties = [_]ScriptProperties{
  .{ .tag = fourcc("    "), .shaper = .default },
  .{ .tag = fourcc("adlm"), .shaper = .use },
  .{ .tag = fourcc("ahom"), .shaper = .use },
  .{ .tag = fourcc("hluw"), .shaper = .default },
  .{ .tag = fourcc("arab"), .shaper = .arabic },
  .{ .tag = fourcc("armn"), .shaper = .default },
  .{ .tag = fourcc("avst"), .shaper = .use },
  .{ .tag = fourcc("bali"), .shaper = .use },
  .{ .tag = fourcc("bamu"), .shaper = .default },
  .{ .tag = fourcc("bass"), .shaper = .use },
  .{ .tag = fourcc("batk"), .shaper = .use },
  .{ .tag = fourcc("bng2"), .shaper = .indic },
  .{ .tag = fourcc("bhks"), .shaper = .use },
  .{ .tag = fourcc("bopo"), .shaper = .default },
  .{ .tag = fourcc("brah"), .shaper = .use },
  .{ .tag = fourcc("bugi"), .shaper = .use },
  .{ .tag = fourcc("buhd"), .shaper = .use },
  .{ .tag = fourcc("cans"), .shaper = .default },
  .{ .tag = fourcc("cari"), .shaper = .default },
  .{ .tag = fourcc("aghb"), .shaper = .default },
  .{ .tag = fourcc("cakm"), .shaper = .use },
  .{ .tag = fourcc("cham"), .shaper = .use },
  .{ .tag = fourcc("cher"), .shaper = .default },
  .{ .tag = fourcc("chrs"), .shaper = .use },
  .{ .tag = fourcc("hani"), .shaper = .default },
  .{ .tag = fourcc("copt"), .shaper = .use },
  .{ .tag = fourcc("cprt"), .shaper = .default },
  .{ .tag = fourcc("cpmn"), .shaper = .use },
  .{ .tag = fourcc("cyrl"), .shaper = .default },
  .{ .tag = fourcc("DFLT"), .shaper = .default },
  .{ .tag = fourcc("DFLT"), .shaper = .default },
  .{ .tag = fourcc("dsrt"), .shaper = .default },
  .{ .tag = fourcc("dev2"), .shaper = .indic },
  .{ .tag = fourcc("diak"), .shaper = .use },
  .{ .tag = fourcc("dogr"), .shaper = .use },
  .{ .tag = fourcc("dupl"), .shaper = .use },
  .{ .tag = fourcc("egyp"), .shaper = .use },
  .{ .tag = fourcc("elba"), .shaper = .default },
  .{ .tag = fourcc("elym"), .shaper = .use },
  .{ .tag = fourcc("ethi"), .shaper = .default },
  .{ .tag = fourcc("gara"), .shaper = .use },
  .{ .tag = fourcc("geor"), .shaper = .default },
  .{ .tag = fourcc("glag"), .shaper = .use },
  .{ .tag = fourcc("goth"), .shaper = .default },
  .{ .tag = fourcc("gran"), .shaper = .use },
  .{ .tag = fourcc("grek"), .shaper = .default },
  .{ .tag = fourcc("gjr2"), .shaper = .indic },
  .{ .tag = fourcc("gong"), .shaper = .use },
  .{ .tag = fourcc("gur2"), .shaper = .indic },
  .{ .tag = fourcc("gukh"), .shaper = .use },
  .{ .tag = fourcc("hang"), .shaper = .hangul },
  .{ .tag = fourcc("rohg"), .shaper = .use },
  .{ .tag = fourcc("hano"), .shaper = .use },
  .{ .tag = fourcc("hatr"), .shaper = .use },
  .{ .tag = fourcc("hebr"), .shaper = .hebrew },
  .{ .tag = fourcc("kana"), .shaper = .default },
  .{ .tag = fourcc("armi"), .shaper = .use },
  .{ .tag = fourcc("phli"), .shaper = .default },
  .{ .tag = fourcc("prti"), .shaper = .default },
  .{ .tag = fourcc("java"), .shaper = .use },
  .{ .tag = fourcc("kthi"), .shaper = .use },
  .{ .tag = fourcc("knd2"), .shaper = .indic },
  .{ .tag = fourcc("kana"), .shaper = .default },
  .{ .tag = fourcc("kawi"), .shaper = .use },
  .{ .tag = fourcc("kali"), .shaper = .use },
  .{ .tag = fourcc("khar"), .shaper = .use },
  .{ .tag = fourcc("kits"), .shaper = .use },
  .{ .tag = fourcc("khmr"), .shaper = .khmer },
  .{ .tag = fourcc("khoj"), .shaper = .use },
  .{ .tag = fourcc("sind"), .shaper = .use },
  .{ .tag = fourcc("krai"), .shaper = .use },
  .{ .tag = fourcc("lao "), .shaper = .default },
  .{ .tag = fourcc("latn"), .shaper = .default },
  .{ .tag = fourcc("lepc"), .shaper = .use },
  .{ .tag = fourcc("limb"), .shaper = .use },
  .{ .tag = fourcc("lina"), .shaper = .default },
  .{ .tag = fourcc("linb"), .shaper = .default },
  .{ .tag = fourcc("lisu"), .shaper = .use },
  .{ .tag = fourcc("lyci"), .shaper = .use },
  .{ .tag = fourcc("lydi"), .shaper = .default },
  .{ .tag = fourcc("mahj"), .shaper = .use },
  .{ .tag = fourcc("maka"), .shaper = .use },
  .{ .tag = fourcc("mlm2"), .shaper = .indic },
  .{ .tag = fourcc("mand"), .shaper = .use },
  .{ .tag = fourcc("mani"), .shaper = .use },
  .{ .tag = fourcc("marc"), .shaper = .use },
  .{ .tag = fourcc("gonm"), .shaper = .use },
  .{ .tag = fourcc("medf"), .shaper = .use },
  .{ .tag = fourcc("mtei"), .shaper = .use },
  .{ .tag = fourcc("mend"), .shaper = .use },
  .{ .tag = fourcc("merc"), .shaper = .use },
  .{ .tag = fourcc("mero"), .shaper = .use },
  .{ .tag = fourcc("plrd"), .shaper = .use },
  .{ .tag = fourcc("modi"), .shaper = .use },
  .{ .tag = fourcc("mong"), .shaper = .use },
  .{ .tag = fourcc("mroo"), .shaper = .default },
  .{ .tag = fourcc("mult"), .shaper = .use },
  .{ .tag = fourcc("mym2"), .shaper = .myanmar },
  .{ .tag = fourcc("nbat"), .shaper = .default },
  .{ .tag = fourcc("nagm"), .shaper = .use },
  .{ .tag = fourcc("nand"), .shaper = .use },
  .{ .tag = fourcc("newa"), .shaper = .use },
  .{ .tag = fourcc("talu"), .shaper = .use },
  .{ .tag = fourcc("nko "), .shaper = .use },
  .{ .tag = fourcc("nshu"), .shaper = .default },
  .{ .tag = fourcc("hmnp"), .shaper = .use },
  .{ .tag = fourcc("ogam"), .shaper = .default },
  .{ .tag = fourcc("olck"), .shaper = .use },
  .{ .tag = fourcc("onao"), .shaper = .use },
  .{ .tag = fourcc("ital"), .shaper = .default },
  .{ .tag = fourcc("hung"), .shaper = .default },
  .{ .tag = fourcc("narb"), .shaper = .use },
  .{ .tag = fourcc("perm"), .shaper = .default },
  .{ .tag = fourcc("xpeo"), .shaper = .use },
  .{ .tag = fourcc("sogo"), .shaper = .use },
  .{ .tag = fourcc("sarb"), .shaper = .default },
  .{ .tag = fourcc("orkh"), .shaper = .default },
  .{ .tag = fourcc("ougr"), .shaper = .use },
  .{ .tag = fourcc("ory2"), .shaper = .indic },
  .{ .tag = fourcc("osge"), .shaper = .use },
  .{ .tag = fourcc("osma"), .shaper = .default },
  .{ .tag = fourcc("hmng"), .shaper = .use },
  .{ .tag = fourcc("palm"), .shaper = .default },
  .{ .tag = fourcc("pauc"), .shaper = .default },
  .{ .tag = fourcc("phag"), .shaper = .use },
  .{ .tag = fourcc("phnx"), .shaper = .default },
  .{ .tag = fourcc("phlp"), .shaper = .use },
  .{ .tag = fourcc("rjng"), .shaper = .use },
  .{ .tag = fourcc("runr"), .shaper = .default },
  .{ .tag = fourcc("samr"), .shaper = .default },
  .{ .tag = fourcc("saur"), .shaper = .use },
  .{ .tag = fourcc("shrd"), .shaper = .use },
  .{ .tag = fourcc("shaw"), .shaper = .default },
  .{ .tag = fourcc("sidd"), .shaper = .use },
  .{ .tag = fourcc("sgnw"), .shaper = .use },
  .{ .tag = fourcc("sogd"), .shaper = .use },
  .{ .tag = fourcc("sinh"), .shaper = .use },
  .{ .tag = fourcc("sora"), .shaper = .use },
  .{ .tag = fourcc("soyo"), .shaper = .use },
  .{ .tag = fourcc("xsux"), .shaper = .use },
  .{ .tag = fourcc("sund"), .shaper = .use },
  .{ .tag = fourcc("sunu"), .shaper = .use },
  .{ .tag = fourcc("sylo"), .shaper = .use },
  .{ .tag = fourcc("syrc"), .shaper = .arabic },
  .{ .tag = fourcc("tglg"), .shaper = .use },
  .{ .tag = fourcc("tagb"), .shaper = .use },
  .{ .tag = fourcc("tale"), .shaper = .use },
  .{ .tag = fourcc("lana"), .shaper = .use },
  .{ .tag = fourcc("tavt"), .shaper = .use },
  .{ .tag = fourcc("takr"), .shaper = .use },
  .{ .tag = fourcc("tml2"), .shaper = .indic },
  .{ .tag = fourcc("tnsa"), .shaper = .use },
  .{ .tag = fourcc("tang"), .shaper = .use },
  .{ .tag = fourcc("tel2"), .shaper = .indic },
  .{ .tag = fourcc("thaa"), .shaper = .default },
  .{ .tag = fourcc("thai"), .shaper = .default },
  .{ .tag = fourcc("tibt"), .shaper = .tibetan },
  .{ .tag = fourcc("tfng"), .shaper = .use },
  .{ .tag = fourcc("tirh"), .shaper = .use },
  .{ .tag = fourcc("todr"), .shaper = .use },
  .{ .tag = fourcc("toto"), .shaper = .use },
  .{ .tag = fourcc("tutg"), .shaper = .use },
  .{ .tag = fourcc("ugar"), .shaper = .default },
  .{ .tag = fourcc("vai "), .shaper = .default },
  .{ .tag = fourcc("vith"), .shaper = .use },
  .{ .tag = fourcc("wcho"), .shaper = .use },
  .{ .tag = fourcc("wara"), .shaper = .use },
  .{ .tag = fourcc("yezi"), .shaper = .use },
  .{ .tag = fourcc("yi  "), .shaper = .default },
  .{ .tag = fourcc("zanb"), .shaper = .use },
};

pub const Language = enum(u32) {
  dont_know = 0,
  a_hmao = fourcc("HMD "),
  aari = fourcc("ARI "),
  abaza = fourcc("ABA "),
  abkhazian = fourcc("ABK "),
  achi = fourcc("ACR "),
  acholi = fourcc("ACH "),
  adyghe = fourcc("ADY "),
  afar = fourcc("AFR "),
  afrikaans = fourcc("AFK "),
  agaw = fourcc("AGW "),
  aiton = fourcc("AIO "),
  akan = fourcc("AKA "),
  albanian = fourcc("SQI "),
  alsatian = fourcc("ALS "),
  altai = fourcc("ALT "),
  aluo = fourcc("YNA "),
  american_phonetic = fourcc("APPH"),
  amharic = fourcc("AMH "),
  anglo_saxon = fourcc("ANG "),
  arabic = fourcc("ARA "),
  aragonese = fourcc("ARG "),
  arakanese = fourcc("ARK "),
  arakwal = fourcc("RKW "),
  armenian = fourcc("HYE "),
  armenian_east = fourcc("HYE0"),
  aromanian = fourcc("RUP "),
  arpitan = fourcc("FRP "),
  assamese = fourcc("ASM "),
  asturian = fourcc("AST "),
  athapaskan = fourcc("ATH "),
  atsina = fourcc("ATS "),
  avar = fourcc("AVR "),
  avatime = fourcc("AVN "),
  awadhi = fourcc("AWA "),
  aymara = fourcc("AYM "),
  azerbaidjani = fourcc("AZE "),
  badaga = fourcc("BAD "),
  baghelkhandi = fourcc("BAG "),
  bagri = fourcc("BGQ "),
  balante = fourcc("BLN "),
  balinese = fourcc("BAN "),
  balkar = fourcc("BAL "),
  balti = fourcc("BLT "),
  baluchi = fourcc("BLI "),
  bambara = fourcc("BMB "),
  bamileke = fourcc("BML "),
  banda = fourcc("BAD0"),
  bandjalang = fourcc("BDY "),
  bangla = fourcc("BEN "),
  bashkir = fourcc("BSH "),
  basque = fourcc("EUQ "),
  batak = fourcc("BTK "),
  batak_alas_kluet = fourcc("BTZ "),
  batak_angkola = fourcc("AKB "),
  batak_dairi = fourcc("BTD "),
  batak_karo = fourcc("BTX "),
  batak_mandailing = fourcc("BTM "),
  batak_simalungun = fourcc("BTS "),
  batak_toba = fourcc("BBC "),
  baule = fourcc("BAU "),
  bavarian = fourcc("BAR "),
  belarusian = fourcc("BEL "),
  bemba = fourcc("BEM "),
  bench = fourcc("BCH "),
  berber = fourcc("BBR "),
  beti = fourcc("BTI "),
  bette_kuruma = fourcc("XUB "),
  bhili = fourcc("BHI "),
  bhojpuri = fourcc("BHO "),
  bhutanese = fourcc("DZN "),
  bible_cree = fourcc("BCR "),
  bikol = fourcc("BIK "),
  bilen = fourcc("BIL "),
  bishnupriya_manipuri = fourcc("BPY "),
  bislama = fourcc("BIS "),
  blackfoot = fourcc("BKF "),
  bodo = fourcc("BRX "),
  bosnian = fourcc("BOS "),
  bouyei = fourcc("PCC "),
  brahui = fourcc("BRH "),
  braj_bhasha = fourcc("BRI "),
  breton = fourcc("BRE "),
  bugis = fourcc("BUG "),
  bulgarian = fourcc("BGR "),
  bumthangkha = fourcc("KJZ "),
  burmese = fourcc("BRM "),
  burushaski = fourcc("BSK "),
  cajun_french = fourcc("FRC "),
  carrier = fourcc("CRR "),
  catalan = fourcc("CAT "),
  cayuga = fourcc("CAY "),
  cebuano = fourcc("CEB "),
  central_yupik = fourcc("ESU "),
  chaha_gurage = fourcc("CHG "),
  chamorro = fourcc("CHA "),
  chattisgarhi = fourcc("CHH "),
  chechen = fourcc("CHE "),
  cherokee = fourcc("CHR "),
  cheyenne = fourcc("CHY "),
  chichewa = fourcc("CHI "),
  chiga = fourcc("CGG "),
  chimila = fourcc("CBG "),
  chin = fourcc("QIN "),
  chinantec = fourcc("CCHN"),
  chinese_phonetic = fourcc("ZHP "),
  chinese_simplified = fourcc("ZHS "),
  chinese_traditional = fourcc("ZHT "),
  chinese_traditional_hong_kong = fourcc("ZHH "),
  chinese_traditional_macao = fourcc("ZHTM"),
  chipewyan = fourcc("CHP "),
  chittagonian = fourcc("CTG "),
  choctaw = fourcc("CHO "),
  chukchi = fourcc("CHK "),
  church_slavonic = fourcc("CSL "),
  chuukese = fourcc("CHK0"),
  chuvash = fourcc("CHU "),
  comorian = fourcc("CMR "),
  comox = fourcc("COO "),
  coptic = fourcc("COP "),
  cornish = fourcc("COR "),
  corsican = fourcc("COS "),
  cree = fourcc("CRE "),
  creoles = fourcc("CPP "),
  crimean_tatar = fourcc("CRT "),
  crioulo = fourcc("KEA "),
  croatian = fourcc("HRV "),
  cypriot_arabic = fourcc("ACY "),
  czech = fourcc("CSY "),
  dagbani = fourcc("DAG "),
  dan = fourcc("DNJ "),
  dangme = fourcc("DNG "),
  danish = fourcc("DAN "),
  dargwa = fourcc("DAR "),
  dari = fourcc("DRI "),
  dayi = fourcc("DAX "),
  default = fourcc("dflt"),
  dehong_dai = fourcc("TDD "),
  dhangu = fourcc("DHG "),
  dhivehi = fourcc("DIV "),
  dhuwal = fourcc("DUJ "),
  dimli = fourcc("DIQ "),
  dinka = fourcc("DNK "),
  djambarrpuyngu = fourcc("DJR0"),
  dogri = fourcc("DGO "),
  dogri_macrolanguage = fourcc("DGR "),
  dungan = fourcc("DUN "),
  dutch = fourcc("NLD "),
  eastern_abenaki = fourcc("AAQ "),
  eastern_cham = fourcc("CJM "),
  eastern_cree = fourcc("ECR "),
  eastern_maninkakan = fourcc("EMK "),
  eastern_pwo_karen = fourcc("KJP "),
  ebira = fourcc("EBI "),
  edo = fourcc("EDO "),
  efik = fourcc("EFI "),
  embera_baudo = fourcc("BDC "),
  embera_catio = fourcc("CTO "),
  embera_chami = fourcc("CMI "),
  embera_tado = fourcc("TDC "),
  english = fourcc("ENG "),
  epena = fourcc("SJA "),
  erzya = fourcc("ERZ "),
  esperanto = fourcc("NTO "),
  estonian = fourcc("ETI "),
  even = fourcc("EVN "),
  evenki = fourcc("EVK "),
  ewe = fourcc("EWE "),
  falam_chin = fourcc("HAL "),
  fang = fourcc("FAN0"),
  fanti = fourcc("FAT "),
  faroese = fourcc("FOS "),
  fefe = fourcc("FMP "),
  fijian = fourcc("FJI "),
  filipino = fourcc("PIL "),
  finnish = fourcc("FIN "),
  flemish = fourcc("FLE "),
  fon = fourcc("FON "),
  forest_enets = fourcc("FNE "),
  french = fourcc("FRA "),
  french_antillean = fourcc("FAN "),
  frisian = fourcc("FRI "),
  friulian = fourcc("FRL "),
  fulah = fourcc("FUL "),
  futa = fourcc("FTA "),
  ga = fourcc("GAD "),
  gagauz = fourcc("GAG "),
  galician = fourcc("GAL "),
  ganda = fourcc("LUG "),
  garhwali = fourcc("GAW "),
  garo = fourcc("GRO "),
  garshuni = fourcc("GAR "),
  geba_karen = fourcc("KVQ "),
  geez = fourcc("GEZ "),
  georgian = fourcc("KAT "),
  gepo = fourcc("YGP "),
  german = fourcc("DEU "),
  gikuyu = fourcc("KIK "),
  gilaki = fourcc("GLK "),
  gilbertese = fourcc("GIL0"),
  gilyak = fourcc("GIL "),
  githabul = fourcc("GIH "),
  gogo = fourcc("GOG "),
  gondi = fourcc("GON "),
  greek = fourcc("ELL "),
  greenlandic = fourcc("GRN "),
  guarani = fourcc("GUA "),
  guinea = fourcc("GKP "),
  gujarati = fourcc("GUJ "),
  gumatj = fourcc("GNN "),
  gumuz = fourcc("GMZ "),
  gupapuyngu = fourcc("GUF "),
  gusii = fourcc("GUZ "),
  haida = fourcc("HAI0"),
  haitian_creole = fourcc("HAI "),
  halkomelem = fourcc("HUR "),
  hammer_banna = fourcc("HBN "),
  harari = fourcc("HRI "),
  harauti = fourcc("HAR "),
  haryanvi = fourcc("BGC "),
  hausa = fourcc("HAU "),
  havasupai_walapai_yavapai = fourcc("YUF "),
  hawaiian = fourcc("HAW "),
  haya = fourcc("HAY "),
  hazaragi = fourcc("HAZ "),
  hebrew = fourcc("IWR "),
  heiltsuk = fourcc("HEI "),
  herero = fourcc("HER "),
  high_mari = fourcc("HMA "),
  hiligaynon = fourcc("HIL "),
  hindi = fourcc("HIN "),
  hindko = fourcc("HND "),
  hiri_motu = fourcc("HMO "),
  hmong = fourcc("HMN "),
  hmong_daw = fourcc("MWW "),
  hmong_shuat = fourcc("HMZ "),
  ho = fourcc("HO  "),
  hungarian = fourcc("HUN "),
  iban = fourcc("IBA "),
  ibibio = fourcc("IBB "),
  icelandic = fourcc("ISL "),
  ido = fourcc("IDO "),
  igbo = fourcc("IBO "),
  ijo = fourcc("IJO "),
  ilokano = fourcc("ILO "),
  inari_sami = fourcc("ISM "),
  indonesian = fourcc("IND "),
  ingush = fourcc("ING "),
  interlingua = fourcc("INA "),
  interlingue = fourcc("ILE "),
  inuktitut = fourcc("INU "),
  inupiat = fourcc("IPK "),
  ipa_phonetic = fourcc("IPP "),
  irish = fourcc("IRI "),
  irish_traditional = fourcc("IRT "),
  irula = fourcc("IRU "),
  italian = fourcc("ITA "),
  jamaican_creole = fourcc("JAM "),
  japanese = fourcc("JAN "),
  javanese = fourcc("JAV "),
  jennu_kuruma = fourcc("XUJ "),
  judeo_tat = fourcc("JDT "),
  jula = fourcc("JUL "),
  kabardian = fourcc("KAB "),
  kabyle = fourcc("KAB0"),
  kachchi = fourcc("KAC "),
  kadiweu = fourcc("KBC "),
  kalenjin = fourcc("KAL "),
  kalmyk = fourcc("KLM "),
  kamba = fourcc("KMB "),
  kanauji = fourcc("BJJ "),
  kannada = fourcc("KAN "),
  kanuri = fourcc("KNR "),
  kaqchikel = fourcc("CAK "),
  karachay = fourcc("KAR "),
  karaim = fourcc("KRM "),
  karakalpak = fourcc("KRK "),
  karelian = fourcc("KRL "),
  karen = fourcc("KRN "),
  kashmiri = fourcc("KSH "),
  kashubian = fourcc("CSB "),
  kate = fourcc("KMG "),
  kazakh = fourcc("KAZ "),
  kebena = fourcc("KEB "),
  kekchi = fourcc("KEK "),
  khakass = fourcc("KHA "),
  khamti_shan = fourcc("KHT "),
  khamyang = fourcc("KSU "),
  khanty_kazim = fourcc("KHK "),
  khanty_shurishkar = fourcc("KHS "),
  khanty_vakhi = fourcc("KHV "),
  khasi = fourcc("KSI "),
  khengkha = fourcc("XKF "),
  khinalug = fourcc("KJJ "),
  khmer = fourcc("KHM "),
  khorasani_turkic = fourcc("KMZ "),
  khowar = fourcc("KHW "),
  khutsuri_georgian = fourcc("KGE "),
  kiche = fourcc("QUC "),
  kikongo = fourcc("KON "),
  kildin_sami = fourcc("KSM "),
  kinyarwanda = fourcc("RUA "),
  kirmanjki = fourcc("KIU "),
  kisii = fourcc("KIS "),
  kituba = fourcc("MKW "),
  kodagu = fourcc("KOD "),
  kokni = fourcc("KKN "),
  komi = fourcc("KOM "),
  komi_permyak = fourcc("KOP "),
  komi_zyrian = fourcc("KOZ "),
  komo = fourcc("KMO "),
  komso = fourcc("KMS "),
  kongo = fourcc("KON0"),
  konkani = fourcc("KOK "),
  koorete = fourcc("KRT "),
  korean = fourcc("KOR "),
  koreao_old_hangul = fourcc("KOH "),
  koryak = fourcc("KYK "),
  kosraean = fourcc("KOS "),
  kpelle = fourcc("KPL "),
  kpelle_liberia = fourcc("XPE "),
  krio = fourcc("KRI "),
  krymchak = fourcc("JCT "),
  kuanyama = fourcc("KUA "),
  kube = fourcc("KGF "),
  kui = fourcc("KUI "),
  kulvi = fourcc("KUK "),
  kumaoni = fourcc("KMN "),
  kumyk = fourcc("KUM "),
  kurdish = fourcc("KUR "),
  kurukh = fourcc("KUU "),
  kuy = fourcc("KUY "),
  kwakwala = fourcc("KWK "),
  kyrgyz = fourcc("KIR "),
  l_cree = fourcc("LCR "),
  ladakhi = fourcc("LDK "),
  ladin = fourcc("LAD "),
  ladino = fourcc("JUD "),
  lahuli = fourcc("LAH "),
  lak = fourcc("LAK "),
  laki = fourcc("LKI "),
  lambani = fourcc("LAM "),
  lampung = fourcc("LJP "),
  lao = fourcc("LAO "),
  latin = fourcc("LAT "),
  latvian = fourcc("LVI "),
  laz = fourcc("LAZ "),
  lelemi = fourcc("LEF "),
  lezgi = fourcc("LEZ "),
  ligurian = fourcc("LIJ "),
  limbu = fourcc("LMB "),
  limburgish = fourcc("LIM "),
  lingala = fourcc("LIN "),
  lipo = fourcc("LPO "),
  lisu = fourcc("LIS "),
  lithuanian = fourcc("LTH "),
  liv = fourcc("LIV "),
  lojban = fourcc("JBO "),
  loma = fourcc("LOM "),
  lombard = fourcc("LMO "),
  lomwe = fourcc("LMW "),
  low_mari = fourcc("LMA "),
  low_saxon = fourcc("NDS "),
  lower_sorbian = fourcc("LSB "),
  lu = fourcc("XBD "),
  luba_katanga = fourcc("LUB "),
  luba_lulua = fourcc("LUA "),
  lule_sami = fourcc("LSM "),
  luo = fourcc("LUO "),
  luri = fourcc("LRC "),
  lushootseed = fourcc("LUT "),
  luxembourgish = fourcc("LTZ "),
  luyia = fourcc("LUH "),
  macedonian = fourcc("MKD "),
  madura = fourcc("MAD "),
  magahi = fourcc("MAG "),
  maithili = fourcc("MTH "),
  majang = fourcc("MAJ "),
  makasar = fourcc("MKR "),
  makhuwa = fourcc("MAK "),
  makonde = fourcc("KDE "),
  malagasy = fourcc("MLG "),
  malay = fourcc("MLY "),
  malayalam = fourcc("MAL "),
  malayalam_reformed = fourcc("MLR "),
  male = fourcc("MLE "),
  malinke = fourcc("MLN "),
  maltese = fourcc("MTS "),
  mam = fourcc("MAM "),
  manchu = fourcc("MCH "),
  mandar = fourcc("MDR "),
  mandinka = fourcc("MND "),
  maninka = fourcc("MNK "),
  manipuri = fourcc("MNI "),
  mano = fourcc("MEV "),
  mansi = fourcc("MAN "),
  manx = fourcc("MNX "),
  maori = fourcc("MRI "),
  mapudungun = fourcc("MAP "),
  marathi = fourcc("MAR "),
  marshallese = fourcc("MAH "),
  marwari = fourcc("MAW "),
  mayan = fourcc("MYN "),
  mazanderani = fourcc("MZN "),
  mbembe_tigon = fourcc("NZA "),
  mbo = fourcc("MBO "),
  mbundu = fourcc("MBN "),
  medumba = fourcc("BYV "),
  meen = fourcc("MEN "),
  mende = fourcc("MDE "),
  meru = fourcc("MER "),
  mewati = fourcc("WTM "),
  minangkabau = fourcc("MIN "),
  minjangbal = fourcc("XJB "),
  mirandese = fourcc("MWL "),
  mizo = fourcc("MIZ "),
  mohawk = fourcc("MOH "),
  moksha = fourcc("MOK "),
  moldavian = fourcc("MOL "),
  mon = fourcc("MON "),
  mongolian = fourcc("MNG "),
  moose_cree = fourcc("MCR "),
  morisyen = fourcc("MFE "),
  moroccan = fourcc("MOR "),
  mossi = fourcc("MPS "),
  mundari = fourcc("MUN "),
  muscogee = fourcc("MUS "),
  n_cree = fourcc("NCR "),
  naga_assamese = fourcc("NAG "),
  nagari = fourcc("NGR "),
  nahuatl = fourcc("NAH "),
  nanai = fourcc("NAN "),
  naskapi = fourcc("NAS "),
  nauruan = fourcc("NAU "),
  navajo = fourcc("NAV "),
  ndau = fourcc("NDC "),
  ndebele = fourcc("NDB "),
  ndonga = fourcc("NDG "),
  neapolitan = fourcc("NAP "),
  nepali = fourcc("NEP "),
  newari = fourcc("NEW "),
  ngbaka = fourcc("NGA "),
  nigerian_fulfulde = fourcc("FUV "),
  nimadi = fourcc("NOE "),
  nisi = fourcc("NIS "),
  niuean = fourcc("NIU "),
  nko = fourcc("NKO "),
  nogai = fourcc("NOG "),
  norfolk = fourcc("PIH "),
  north_slavey = fourcc("SCS "),
  northern_embera = fourcc("EMP "),
  northern_sami = fourcc("NSM "),
  northern_sotho = fourcc("NSO "),
  northern_tai = fourcc("NTA "),
  norway_house_cree = fourcc("NHC "),
  norwegian = fourcc("NOR "),
  norwegian_nynorsk = fourcc("NYN "),
  novial = fourcc("NOV "),
  numanggang = fourcc("NOP "),
  nuu_chah_nulth = fourcc("NUK "),
  nyamwezi = fourcc("NYM "),
  nyankole = fourcc("NKL "),
  occitan = fourcc("OCI "),
  odia = fourcc("ORI "),
  oji_cree = fourcc("OCR "),
  ojibway = fourcc("OJB "),
  old_irish = fourcc("SGA "),
  old_javanese = fourcc("KAW "),
  oneida = fourcc("ONE "),
  onondaga = fourcc("ONO "),
  oromo = fourcc("ORO "),
  ossetian = fourcc("OSS "),
  pa_o_karen = fourcc("BLK "),
  palauan = fourcc("PAU "),
  palaung = fourcc("PLG "),
  palestinian_aramaic = fourcc("PAA "),
  pali = fourcc("PAL "),
  palpa = fourcc("PAP "),
  pampangan = fourcc("PAM "),
  pangasinan = fourcc("PAG "),
  papiamentu = fourcc("PAP0"),
  pashto = fourcc("PAS "),
  pattani_malay = fourcc("MFA "),
  pennsylvania_german = fourcc("PDC "),
  persian = fourcc("FAR "),
  phake = fourcc("PJK "),
  picard = fourcc("PCD "),
  piemontese = fourcc("PMS "),
  pite_sami = fourcc("SJE "),
  pocomchi = fourcc("POH "),
  pohnpeian = fourcc("PON "),
  polish = fourcc("PLK "),
  polytonic_greek = fourcc("PGR "),
  portuguese = fourcc("PTG "),
  provencal = fourcc("PRO "),
  punjabi = fourcc("PAN "),
  quechua = fourcc("QUZ "),
  quechua_bolivia = fourcc("QUH "),
  quechua_ecuador = fourcc("QVI "),
  quechua_peru = fourcc("QWH "),
  r_cree = fourcc("RCR "),
  rajasthani = fourcc("RAJ "),
  rarotongan = fourcc("RAR "),
  rejang = fourcc("REJ "),
  riang = fourcc("RIA "),
  ritarungo = fourcc("RIT "),
  rohingya = fourcc("RHG "),
  romanian = fourcc("ROM "),
  romansh = fourcc("RMS "),
  romany = fourcc("ROY "),
  rotuman = fourcc("RTM "),
  rundi = fourcc("RUN "),
  russian = fourcc("RUS "),
  russian_buriat = fourcc("RBU "),
  rusyn = fourcc("RSY "),
  sadri = fourcc("SAD "),
  sakha = fourcc("YAK "),
  samoan = fourcc("SMO "),
  samogitian = fourcc("SGS "),
  san_blas_kuna = fourcc("CUK "),
  sango = fourcc("SGO "),
  sanskrit = fourcc("SAN "),
  santali = fourcc("SAT "),
  saraiki = fourcc("SRK "),
  sardinian = fourcc("SRD "),
  sasak = fourcc("SAS "),
  saterland_frisian = fourcc("STQ "),
  sayisi = fourcc("SAY "),
  scots = fourcc("SCI "),
  scottish_gaelic = fourcc("GAE "),
  sekota = fourcc("SEJ "),
  selkup = fourcc("SEL "),
  sena = fourcc("SNA "),
  seneca = fourcc("SEE "),
  serbian = fourcc("SRB "),
  serer = fourcc("SRR "),
  sgaw_karen = fourcc("KSW "),
  shan = fourcc("SHN "),
  sibe = fourcc("SIB "),
  sicilian = fourcc("SCN "),
  sidamo = fourcc("SID "),
  silesian = fourcc("SZL "),
  silte_gurage = fourcc("SIG "),
  sindhi = fourcc("SND "),
  sinhala = fourcc("SNH "),
  skolt_sami = fourcc("SKS "),
  slavey = fourcc("SLA "),
  slovak = fourcc("SKY "),
  slovenian = fourcc("SLV "),
  small_flowery_miao = fourcc("SFM "),
  sodo_gurage = fourcc("SOG "),
  soga = fourcc("XOG "),
  somali = fourcc("SML "),
  songe = fourcc("SOP "),
  soninke = fourcc("SNK "),
  south_slavey = fourcc("SSL "),
  southern_kiwai = fourcc("KJD "),
  southern_sami = fourcc("SSM "),
  southern_sotho = fourcc("SOT "),
  spanish = fourcc("ESP "),
  standard_moroccan_tamazight = fourcc("ZGH "),
  straits_salish = fourcc("STR "),
  sukuma = fourcc("SUK "),
  sundanese = fourcc("SUN "),
  suri = fourcc("SUR "),
  sutu = fourcc("SXT "),
  svan = fourcc("SVA "),
  swadaya_aramaic = fourcc("SWA "),
  swahili = fourcc("SWK "),
  swati = fourcc("SWZ "),
  swedish = fourcc("SVE "),
  sylheti = fourcc("SYL "),
  syriac = fourcc("SYR "),
  syriac_eastern = fourcc("SYRN"),
  syriac_estrangela = fourcc("SYRE"),
  syriac_western = fourcc("SYRJ"),
  tabasaran = fourcc("TAB "),
  tachelhit = fourcc("SHI "),
  tagalog = fourcc("TGL "),
  tahaggart_tamahaq = fourcc("THV "),
  tahitian = fourcc("THT "),
  tai_laing = fourcc("TJL "),
  tajiki = fourcc("TAJ "),
  talysh = fourcc("TLY "),
  tamashek = fourcc("TMH "),
  tamasheq = fourcc("TAQ "),
  tamazight = fourcc("TZM "),
  tamil = fourcc("TAM "),
  tarifit = fourcc("RIF "),
  tatar = fourcc("TAT "),
  tawallammat_tamajaq = fourcc("TTQ "),
  tay = fourcc("TYZ "),
  tayart_tamajeq = fourcc("THZ "),
  telugu = fourcc("TEL "),
  temne = fourcc("TMN "),
  tetum = fourcc("TET "),
  th_cree = fourcc("TCR "),
  thai = fourcc("THA "),
  thailand_mon = fourcc("MONT"),
  thompson = fourcc("THP "),
  tibetan = fourcc("TIB "),
  tigre = fourcc("TGR "),
  tigrinya = fourcc("TGY "),
  tiv = fourcc("TIV "),
  tlingit = fourcc("TLI "),
  tobo = fourcc("TBV "),
  todo = fourcc("TOD "),
  tok_pisin = fourcc("TPI "),
  toma = fourcc("TOD0"),
  tonga = fourcc("TNG "),
  tongan = fourcc("TGN "),
  torki = fourcc("AZB "),
  tshangla = fourcc("TSJ "),
  tsonga = fourcc("TSG "),
  tswana = fourcc("TNA "),
  tulu = fourcc("TUL "),
  tumbuka = fourcc("TUM "),
  tundra_enets = fourcc("TNE "),
  turkish = fourcc("TRK "),
  turkmen = fourcc("TKM "),
  turoyo_aramaic = fourcc("TUA "),
  tuscarora = fourcc("TUS "),
  tuvalu = fourcc("TVL "),
  tuvin = fourcc("TUV "),
  twi = fourcc("TWI "),
  tzotzil = fourcc("TZO "),
  udi = fourcc("UDI "),
  udmurt = fourcc("UDM "),
  ukrainian = fourcc("UKR "),
  umbundu = fourcc("UMB "),
  ume_sami = fourcc("SJU "),
  upper_saxon = fourcc("SXU "),
  upper_sorbian = fourcc("USB "),
  uralic_phonetic = fourcc("UPP "),
  urdu = fourcc("URD "),
  uyghur = fourcc("UYG "),
  uzbek = fourcc("UZB "),
  venda = fourcc("VEN "),
  venetian = fourcc("VEC "),
  vietnamese = fourcc("VIT "),
  vlax_romani = fourcc("RMY "),
  volapuk = fourcc("VOL "),
  voro = fourcc("VRO "),
  wa = fourcc("WA  "),
  waci_gbe = fourcc("WCI "),
  wagdi = fourcc("WAG "),
  wakhi = fourcc("WBL "),
  walloon = fourcc("WLN "),
  waray_waray = fourcc("WAR "),
  wayanad_chetti = fourcc("CTT "),
  wayuu = fourcc("GUC "),
  welsh = fourcc("WEL "),
  wendat = fourcc("WDT "),
  west_cree = fourcc("WCR "),
  western_cham = fourcc("CJA "),
  western_kayah = fourcc("KYU "),
  western_panjabi = fourcc("PNB "),
  western_pwo_karen = fourcc("PWO "),
  wolof = fourcc("WLF "),
  woods_cree = fourcc("DCR "),
  wuding_luquan_yi = fourcc("YWQ "),
  wyandot = fourcc("WYN "),
  xhosa = fourcc("XHS "),
  y_cree = fourcc("YCR "),
  yao = fourcc("YAO "),
  yapese = fourcc("YAP "),
  yi_classic = fourcc("YIC "),
  yi_modern = fourcc("YIM "),
  yiddish = fourcc("JII "),
  yoruba = fourcc("YBA "),
  zamboanga_chavacano = fourcc("CBK "),
  zande = fourcc("ZND "),
  zarma = fourcc("DJR "),
  zazaki = fourcc("ZZA "),
  zealandic = fourcc("ZEA "),
  zhuang = fourcc("ZHA "),
  zulu = fourcc("ZUL "),
};
