#!/usr/bin/env python3
"""
Cross-language benchmark runner: ink vs ngnk.

Each test/bench/<lang>/<name>.k file runs the benchmark 20 times internally.
This script times each file REPS=5 times, takes the median, and divides by
INNER=20 to get per-iteration ms.

Writes bench/langs.csv and bench/langs.k (ink-loadable data file).

Usage:
  python3 tool/bench_langs.py [--ink PATH] [--ngnk PATH] [--build]
"""

import argparse
import pathlib
import statistics
import subprocess
import sys
import time

ROOT   = pathlib.Path(__file__).parent.parent
INNER  = 20    # iterations baked into each .k file
REPS   = 5     # outer subprocess repetitions for median
TIMEOUT = 60   # seconds per subprocess call

BENCHMARKS = [
    "baseline",
    "sum",
    "max",
    "scan",
    "reverse",
    "sort",
    "distinct",
    "group",
    "dot",
    "count",
    "filter",
    "each",
    "fusion",
]


def run_file(binary: str, k_file: pathlib.Path) -> float | None:
    """Return wall-clock ms for one subprocess run, or None on error/timeout."""
    t0 = time.perf_counter()
    try:
        r = subprocess.run(
            [binary, str(k_file)],
            capture_output=True,
            timeout=TIMEOUT,
        )
    except subprocess.TimeoutExpired:
        return None
    t1 = time.perf_counter()
    return None if r.returncode != 0 else (t1 - t0) * 1000.0


def bench_lang(binary: str, bench_dir: pathlib.Path, label: str) -> dict[str, float | None]:
    results: dict[str, float | None] = {}
    print(f"\n{label}  ({binary})")
    for name in BENCHMARKS:
        k_file = bench_dir / f"{name}.k"
        if not k_file.exists():
            print(f"  {name:<12}  (no file)")
            results[name] = None
            continue
        raw = [run_file(binary, k_file) for _ in range(REPS)]
        valid = [t / INNER for t in raw if t is not None]
        if valid:
            med = statistics.median(valid)
            results[name] = round(med, 4)
            print(f"  {name:<12}  {med:8.3f} ms/iter")
        else:
            results[name] = None
            print(f"  {name:<12}  ERROR")
    return results


def emit_csv(out: pathlib.Path, langs: list[str], all_results: dict) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        f.write("benchmark," + ",".join(langs) + "\n")
        for name in BENCHMARKS:
            row = [name] + [
                str(all_results[lang].get(name) or "")
                for lang in langs
            ]
            f.write(",".join(row) + "\n")
    print(f"\nCSV  → {out}")


def emit_ink_data(out: pathlib.Path, langs: list[str], all_results: dict) -> None:
    """Write an ink-evaluable data file consumed by test/bench/report.k."""
    with open(out, "w") as f:
        f.write("/ generated by tool/bench_langs.py\n")
        names_lit = ";".join(f'"{n}"' for n in BENCHMARKS)
        f.write(f"names:({names_lit})\n")
        for lang in langs:
            vals = all_results[lang]
            nums = " ".join(
                str(vals.get(n) or 0.0) for n in BENCHMARKS
            )
            f.write(f"{lang}_ms:{nums}\n")
    print(f"Data → {out}")


def main() -> None:
    p = argparse.ArgumentParser(description="Cross-language array benchmark runner")
    p.add_argument("--ink",   default=str(ROOT / "zig-out/bin/ink"),
                   help="path to ink binary (default: zig-out/bin/ink)")
    p.add_argument("--ngnk",  default=str(pathlib.Path.home() / ".k/k"),
                   help="path to ngn/k binary (default: ~/.k/k)")
    p.add_argument("--out",   default=str(ROOT / "bench/langs.csv"),
                   help="CSV output path")
    p.add_argument("--build", action="store_true",
                   help="compile ink with -Doptimize=ReleaseFast first")
    args = p.parse_args()

    if args.build:
        print("Building ink with -Doptimize=ReleaseFast …")
        r = subprocess.run(
            ["zig", "build", "-Doptimize=ReleaseFast"],
            cwd=ROOT, capture_output=True, text=True,
        )
        if r.returncode != 0:
            sys.exit(f"Build failed:\n{r.stderr}")
        print("Build OK\n")

    configs = [
        ("ink",  args.ink,  ROOT / "test/bench/ink"),
        ("ngnk", args.ngnk, ROOT / "test/bench/ngnk"),
    ]

    all_results = {
        lang: bench_lang(binary, bench_dir, lang)
        for lang, binary, bench_dir in configs
    }

    langs = [lang for lang, _, _ in configs]
    csv_path = pathlib.Path(args.out)
    emit_csv(csv_path, langs, all_results)
    emit_ink_data(csv_path.with_suffix(".k"), langs, all_results)


if __name__ == "__main__":
    main()
